# Generated by Django 4.2.10 on 2025-04-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='expertise',
            field=models.ManyToManyField(blank=True, related_name='expert_agents', to='tickets.category'),
        ),
    ]
